[package]
name = "gnss_tec_core"
version = "0.4.2"
edition = "2024"
rust-version = "1.88"
description = "Optimized RINEX file parser for the pygnss-tec Python package."
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "gnss_tec_core"

[dependencies]
arrow = { version = "60.0.0", default-features = false, features = ["pyarrow"] }
pyo3 = { version = "0.29.3", features = ["abi3-py312", "extension-module"] }
rayon = "1.12.0"
rinex = { version = "=0.23.2", features = ["flate2", "nav", "qc"] }
rustc-hash = "2.1.3"

[target.'cfg(target_family = "unix")'.dependencies]
tikv-jemallocator = { version = "0.6", optional = true }

[target.'cfg(target_family = "windows")'.dependencies]
mimalloc = { version = "0.1.52", optional = true }

[features]
default = []
custom-alloc = ["mimalloc", "tikv-jemallocator"]

[profile.release]
opt-level = 3
strip = "symbols"
lto = "thin"
panic = "abort"
codegen-units = 1
